name: thirst_alert
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.16
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  pretty_dio_logger: ^1.3.1
  fl_chart: ^0.67.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: lib/assets/ta-app-icon.png

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/
